clear
count=0;
SWITCH1=0;
SWITCHM=0;
TLAUNCH=200.;
XLONGTDEG=7.42;
XLATTDEG=43.75;
XLATFDEG=36.175;
XLONGFDEG=-115.136;
XLONGMDEG=-74.423;
XLATMDEG=39.364;
PREDERR=10.*6076.;
XNCLIM=161.;
XLATMDEGIC=XLATMDEG;
XLONGMDEGIC=XLONGMDEG;
TFTOT=2000.;
TF=1000.;
A=2.0926E7;
GM=1.4077E16;
W=-6.283185/86400.;
QBOOSTM=1;
XLONGF=XLONGFDEG/57.3;
XLATF=XLATFDEG/57.3;
XLONGT=XLONGTDEG/57.3;
XLATT=XLATTDEG/57.3;
XLONGM=XLONGMDEG/57.3;
XLATM=XLATMDEG/57.3;
XLONGF=XLONGF-W*TF;
XF=A*cos(XLATF)*cos(XLONGF);
YF=A*cos(XLATF)*sin(XLONGF);
ZF=A*sin(XLATF);
XT=A*cos(XLATT)*cos(XLONGT);
YT=A*cos(XLATT)*sin(XLONGT);
ZT=A*sin(XLATT);
[XTD,YTD,ZTD]=LAMBERT3D(XT,YT,ZT,TFTOT,XF,YF,ZF,SWITCH1);
XTINIT=XT;
YTINIT=YT;
ZTINIT=ZT;
XM=A*cos(XLATM)*cos(XLONGM);
YM=A*cos(XLATM)*sin(XLONGM);
ZM=A*sin(XLATM);
XMD=A*W*cos(XLATM)*sin(XLONGM);
YMD=-A*W*cos(XLATM)*cos(XLONGM);
ZMD=0.;
RTM1=XT-XM;
RTM2=YT-YM;
RTM3=ZT-ZM;
RTM=sqrt(RTM1^2+RTM2^2+RTM3^2);
VTM1=XTD-XMD;
VTM2=YTD-YMD;
VTM3=ZTD-ZMD;
VC=-(RTM1*VTM1+RTM2*VTM2+RTM3*VTM3)/RTM;
T=0.;
H=.001;
T0=0.;
T1=TF;
X0(1)=XT/3280.;
X0(2)=YT/3280.;
X0(3)=ZT/3280.;
X0(4)=XTD/3280.;
X0(5)=YTD/3280.;
X0(6)=ZTD/3280.;
[X1]=KEPLER1(X0,T0,T1);
XTF=X1(1)*3280.;
YTF=X1(2)*3280.;
ZTF=X1(3)*3280.;
XTF=XTF+PREDERR;
S=0.;
DELV=0.;
ALTNM=(sqrt(XT^2+YT^2+ZT^2)-A)/3280.;
while VC>0 
 	if RTM>5000.
		H=.01;
	else
		H=.00001;
	end
	XTOLD=XT;
	YTOLD=YT;
	ZTOLD=ZT;
	XTDOLD=XTD;
	YTDOLD=YTD;
	ZTDOLD=ZTD;
	XMOLD=XM;
	YMOLD=YM;
	ZMOLD=ZM;
	XMDOLD=XMD;
	YMDOLD=YMD;
	ZMDOLD=ZMD;
	DELVOLD=DELV;
	STEP=1;
	FLAG=0;
	while STEP<=1
		if FLAG==1 
         		STEP=2;
			XT=XT+H*XTD;
			YT=YT+H*YTD;
			ZT=ZT+H*ZTD;
			XTD=XTD+H*XTDD;
			YTD=YTD+H*YTDD;
			ZTD=ZTD+H*ZTDD;
			if T<TLAUNCH & QBOOSTM==1 
				XM=XM;
				YM=YM;
				ZM=ZM;
				XMD=XMD;
				YMD=YMD;
				ZMD=ZMD;
			else
				XM=XM+H*XMD;
				YM=YM+H*YMD;
				ZM=ZM+H*ZMD;
				XMD=XMD+H*XMDD;
				YMD=YMD+H*YMDD;
				ZMD=ZMD+H*ZMDD;
			end
			DELV=DELV+H*DELVD;
        		T=T+H;
        	end
        	TEMPBOTT=(XT^2+YT^2+ZT^2)^1.5;
		XTDD=-GM*XT/TEMPBOTT;
		YTDD=-GM*YT/TEMPBOTT;
		ZTDD=-GM*ZT/TEMPBOTT;
		ALTNM=(sqrt(XT^2+YT^2+ZT^2)-A)/3280.;
		RTM1=XT-XM;
		RTM2=YT-YM;
		RTM3=ZT-ZM;
		VTM1=XTD-XMD;
		VTM2=YTD-YMD;
		VTM3=ZTD-ZMD;
		RTM=sqrt(RTM1^2+RTM2^2+RTM3^2);
		VC=-(RTM1*VTM1+RTM2*VTM2+RTM3*VTM3)/RTM;
		TGO=RTM/VC;
		if TGO<200. & T>(TLAUNCH+50.) 
			ZEM1=RTM1+VTM1*TGO;
			ZEM2=RTM2+VTM2*TGO;
			ZEM3=RTM3+VTM3*TGO;
			ZEMDOTRTM=(ZEM1*RTM1+ZEM2*RTM2+ZEM3*RTM3)/RTM;
			ZEMPER1=ZEM1-ZEMDOTRTM*RTM1/RTM;
			ZEMPER2=ZEM2-ZEMDOTRTM*RTM2/RTM;
			ZEMPER3=ZEM3-ZEMDOTRTM*RTM3/RTM;
			ZEMPERLOSKM=sqrt(ZEMPER1^2+ZEMPER2^2+ZEMPER3^2)/3280.;
			AXMGUID=3.*ZEMPER1/(TGO^2);
			AYMGUID=3.*ZEMPER2/(TGO^2);
			AZMGUID=3.*ZEMPER3/(TGO^2);
		else
			AXMGUID=0.;
			AYMGUID=0.;
			AZMGUID=0.;
		end
		if AXMGUID>XNCLIM 
			AXMGUID=XNCLIM;
		elseif AXMGUID<-XNCLIM
			AXMGUID=-XNCLIM;
		end
		if AYMGUID>XNCLIM 
			AYMGUID=XNCLIM;
		elseif AYMGUID<-XNCLIM 
			AYMGUID=-XNCLIM;
		end
		if AZMGUID>XNCLIM
			AZMGUID=XNCLIM;
		elseif AZMGUID<-XNCLIM 
			AZMGUID=-XNCLIM;
		end
		if T>TLAUNCH 
			TEMPBOTM=(XM^2+YM^2+ZM^2)^1.5;
			XMDD=-GM*XM/TEMPBOTM+AXMGUID;
			YMDD=-GM*YM/TEMPBOTM+AYMGUID;
			ZMDD=-GM*ZM/TEMPBOTM+AZMGUID;
		else
			XMDD=0.;
			YMDD=0.;
			ZMDD=0.;
		end
		DELVD=sqrt(AXMGUID^2+AYMGUID^2+AZMGUID^2);
		FLAG=1;
	end
	FLAG=0;
	XT=.5*(XTOLD+XT+H*XTD);
 	YT=.5*(YTOLD+YT+H*YTD);
	ZT=.5*(ZTOLD+ZT+H*ZTD);
	XTD=.5*(XTDOLD+XTD+H*XTDD);
 	YTD=.5*(YTDOLD+YTD+H*YTDD);
	ZTD=.5*(ZTDOLD+ZTD+H*ZTDD);
	if T<TLAUNCH & QBOOSTM==1
		XM=A*cos(XLATMDEGIC/57.3)*cos(XLONGMDEGIC/57.3-W*T);
		YM=A*cos(XLATMDEGIC/57.3)*sin(XLONGMDEGIC/57.3-W*T);
		ZM=A*sin(XLATMDEGIC/57.3);
		XMD=A*W*cos(XLATMDEGIC/57.3)*sin(XLONGMDEGIC/57.3-W*T);
		YMD=-A*W*cos(XLATMDEGIC/57.3)*cos(XLONGMDEGIC/57.3-W*T);
		ZMD=0.;
	else
		XM=.5*(XMOLD+XM+H*XMD);
 		YM=.5*(YMOLD+YM+H*YMD);
		ZM=.5*(ZMOLD+ZM+H*ZMD);
		XMD=.5*(XMDOLD+XMD+H*XMDD);
 		YMD=.5*(YMDOLD+YMD+H*YMDD);
		ZMD=.5*(ZMDOLD+ZMD+H*ZMDD);
	end
	DELV=.5*(DELVOLD+DELV+H*DELVD);
	TGOM=TF-T;
	if T>=TLAUNCH & QBOOSTM==1
		[XMD,YMD,ZMD]=LAMBERT3D(XM,YM,ZM,TGOM,XTF,YTF,ZTF,SWITCHM);
		QBOOSTM=0;
		XMDOLD=XMD;
		YMDOLD=YMD;
		ZMDOLD=ZMD;
	end
	S=S+H;
	if S>=9.9999
		S=0.;
		XTE=XT*cos(W*T)-YT*sin(W*T);
		YTE=XT*sin(W*T)+YT*cos(W*T);
		ZTE=ZT;
		XLATT=atan2(ZTE, sqrt(XTE^2+YTE^2));
		XLATTDEG=57.3*XLATT;
		XLONGT=atan2(YTE, XTE);
		XLONGTDEG=57.3*XLONGT;
		DISTRTNM=distance3dkm(XTE,YTE,ZTE,XTINIT,YTINIT,ZTINIT);
		XME=XM*cos(W*T)-YM*sin(W*T);
		YME=XM*sin(W*T)+YM*cos(W*T);
		ZME=ZM;
		XLATM=atan2(ZME, sqrt(XME^2+YME^2));
		XLATMDEG=57.3*XLATM;
		XLONGM=atan2(YME, XME);
		XLONGMDEG=57.3*XLONGM;
		DISTRMNM=distance3dkm(XME,YME,ZME,XTINIT,YTINIT,ZTINIT);
		ALTMNM=(sqrt(XM^2+YM^2+ZM^2)-A)/3280.;
		AXMGUIDG=sqrt(AXMGUID^2+AYMGUID^2+AZMGUID^2)/32.2;
		count=count+1;
		ArrayT(count)=T;
		ArrayDISTRTNM(count)=DISTRTNM;
		ArrayALTNM(count)=ALTNM;
		ArrayDISTRMNM(count)=DISTRMNM;
		ArrayALTMNM(count)=ALTMNM;
		ArrayAXMGUIDG(count)=AXMGUIDG;
		ArrayXLONGTDEG(count)=XLONGTDEG;
		ArrayXLATTDEG(count)=XLATTDEG;
		ArrayXLONGMDEG(count)=XLONGMDEG;
		ArrayXLATMDEG(count)=XLATMDEG;
	end
end
XTE=XT*cos(W*T)-YT*sin(W*T);
YTE=XT*sin(W*T)+YT*cos(W*T);
ZTE=ZT;
XLATT=atan2(ZTE, sqrt(XTE^2+YTE^2));
XLATTDEG=57.3*XLATT;
XLONGT=atan2(YTE, XTE);
XLONGTDEG=57.3*XLONGT;
DISTRTNM=distance3dkm(XTE,YTE,ZTE,XTINIT,YTINIT,ZTINIT);
XME=XM*cos(W*T)-YM*sin(W*T);
YME=XM*sin(W*T)+YM*cos(W*T);
ZME=ZM;
XLATM=atan2(ZME, sqrt(XME^2+YME^2));
XLATMDEG=57.3*XLATM;
XLONGM=atan2(YME, XME);
XLONGMDEG=57.3*XLONGM;
DISTRMNM=distance3dkm(XME,YME,ZME,XTINIT,YTINIT,ZTINIT);
ALTMNM=(sqrt(XM^2+YM^2+ZM^2)-A)/3280.;
AXMGUIDG=sqrt(AXMGUID^2+AYMGUID^2+AZMGUID^2)/32.2;
count=count+1;
ArrayT(count)=T;
ArrayDISTRTNM(count)=DISTRTNM;
ArrayALTNM(count)=ALTNM;
ArrayDISTRMNM(count)=DISTRMNM;
ArrayALTMNM(count)=ALTMNM;
ArrayAXMGUIDG(count)=AXMGUIDG;
ArrayXLONGTDEG(count)=XLONGTDEG;
ArrayXLATTDEG(count)=XLATTDEG;
ArrayXLONGMDEG(count)=XLONGMDEG;
ArrayXLATMDEG(count)=XLATMDEG;
RTM
DELV
figure
plot(ArrayDISTRTNM,ArrayALTNM,ArrayDISTRMNM,ArrayALTMNM),grid
xlabel('Downrange (km)')
ylabel('Altitude (km) ')
figure
plot(ArrayT,ArrayAXMGUIDG),grid
xlabel('Time (s))')
ylabel('Acceleration (g) ')
axis([0 1000 0 .5])
clc
output=[ArrayT',ArrayDISTRTNM',ArrayALTNM',ArrayDISTRMNM',ArrayALTMNM',ArrayAXMGUIDG'];
save datfil.txt output -ascii
output=[ArrayT',ArrayXLONGTDEG',ArrayXLATTDEG',ArrayXLONGMDEG',ArrayXLATMDEG'];
csvwrite('trajfil.txt',output)
disp 'simulation finished'
% 3d Kepler and Lambert routines previously presented