clear
count=0;
TLAUNCH=90.;
TF=170.;
TS=1.;
XLONGMDEGICKM=400.;
RDESKM=2000.;
GAMDEG=89.99;
TFTOT=2000.;
TUPT=15.;
TGUID=110.;
XNCLIM=322.;
XNP=3.;
QPERFECT=1;
TLOFT=200.;
ALTMKMIC=15.;
QTAYLOR=1;
PIPERRKM=0.;
QGUID=1;
ITGT=1;
SWITCH1=0;
SWITCHM=0;
DELTF=0.;
QFIX=1;
if ITGT==1
	TPZ=180.;
else
	TPZ=240.;
end
ALTM=ALTMKMIC*3280.;
TFTOT=252.+.223*RDESKM-(5.44E-6)*RDESKM*RDESKM;
TFTOT=TFTOT+TLOFT;
A=2.0926E7;
GM=1.4077E16;
W=0.;
XLONGFDEG=57.3*RDESKM*3280./A;
XLONGMDEGIC=XLONGMDEGICKM/111.;
XLONGMDEG=XLONGMDEGIC;
QLAUNCH=0;
QFIRST=1;
XLONGTDEG=0.;
QBOOST=1;
QOOMPH=1;
T=0.;
S=0.;
AXT=0.;
AYT=0.;
ATP=0.;
XLONGF=XLONGFDEG/57.3;
XLONGF=XLONGF-W*TFTOT;
PIPERR=0.;
XF=A*cos(XLONGF);
YF=A*sin(XLONGF);
ZF=0;
XLONGT=XLONGTDEG/57.3;
XLONGM=XLONGMDEG/57.3;
XT=A*cos(XLONGT);
YT=A*sin(XLONGT);
XTINIT=XT;
YTINIT=YT;
RTINIT=sqrt(XTINIT^2+YTINIT^2);
XM=(A+ALTM)*cos(XLONGM);
YM=(A+ALTM)*sin(XLONGM);
ZM=0;
XFIRST=XT;
YFIRST=YT;
ZT=0;
ZFIRST=0;
DISTRTKMIC=distance3dkm(XT,YT,ZT,XFIRST,YFIRST,ZFIRST);
XMINIT=XM;;
YMINIT=YM;
RMINIT=sqrt(XMINIT^2+YMINIT^2);
XTD=cos(1.5708-GAMDEG/57.3);
YTD=sin(1.5708-GAMDEG/57.3);
ATP=1.;
AXM=0.;
AYM=0.;
AMP=0.;
H=.01;
ALTTKM=(sqrt(XT^2+YT^2)-A)/3280.;
XMD=0.;
YMD=0.;
RTM1=XT-XM;
RTM2=YT-YM;
RTM=sqrt(RTM1^2+RTM2^2);
VTM1=XTD-XMD;
VTM2=YTD-YMD;
VC=-(RTM1*VTM1+RTM2*VTM2)/RTM;
DELV=0.;
ACC=0.;
AXMGUID=0.;
AYMGUID=0.;
PREDERRKM=0.;
ZEM1=0.;
ZEM2=0.;
ALTMKM=(sqrt(XM^2+YM^2)-A)/3280.;
TBOT=0.;
DELVELM=0.;
PIPKMBO=0.;
ZEMPERPTOT=0.;
if QFIX==1
% FIND EXACT LOCATION OF TARGET AT DESIRED INTERCEPT TIME EXACT PIP)
	[XTFACT,YTFACT]=predict45(T,XT,YT,XTD,YTD,TF,TFTOT,TUPT,XF,YF,ITGT);
	ZTFACT=0;
	TGOLAM=TF-TLAUNCH;
	[VRX,VRY,VRZ]=LAMBERT3D(XM,YM,ZM,TGOLAM,XTFACT,YTFACT,ZTFACT,SWITCHM);
	VMXRQD=VRX;
	VMYRQD=VRY;
	VMRQDKM=sqrt(VMXRQD^2+VMYRQD^2)/3280.;
else
	for TF=(TLAUNCH+30.):10:(TPZ-10.),
% FIND EXACT LOCATION OF TARGET AT DESIRED INTERCEPT TIME EXACT PIP)
		[XTFACT,YTFACT]=predict45(T,XT,YT,XTD,YTD,TF,TFTOT,TUPT,XF,YF,ITGT);
		TGOLAM=TF-TLAUNCH;
		[VRX,VRY,VRZ]=LAMBERT3D(XM,YM,ZM,TGOLAM,XTFACT,YTFACT,ZTFACT,SWITCHM);
		VMXRQD=VRX;
		VMYRQD=VRY;
		VMRQDKM=sqrt(VMXRQD^2+VMYRQD^2)/3280.;
		if VMRQDKM<4.
			break
		end
	end
end
TF=TF+DELTF;
while ~((T>(TF-10.)) & VC<0.)
	if RTM<1000
		H=.00001;
	else
		H=.01;
	end
	XTOLD=XT;
	YTOLD=YT;
	XTDOLD=XTD;
	YTDOLD=YTD;
	XMOLD=XM;
	YMOLD=YM;
	XMDOLD=XMD;
	YMDOLD=YMD;
	DELVOLD=DELV;
	STEP=1;
	FLAG=0;
	while STEP <=1
		if FLAG==1
			STEP=2;
			XT=XT+H*XTD;
			YT=YT+H*YTD;
			XTD=XTD+H*XTDD;
			YTD=YTD+H*YTDD;
			XM=XM+H*XMD;
			YM=YM+H*YMD;
			XMD=XMD+H*XMDD;
			YMD=YMD+H*YMDD;
			DELV=DELV+H*DELVD;
			T=T+H;
		end
		if ITGT==1
			if T<180.
				WGT=-212.*T+44000.;
				TRST=54100.;
			else
				WGT=3300.;
				TRST=0.;
			end
		else
			if T<120.
				WGT=-2622*T+440660.;
				TRST=725850.;
			elseif T<240.
				WGT=-642.*T+168120.;
				TRST=182250.;
			else
				WGT=5500.;
				TRST=0.;
			end
		end
		ATP=32.2*TRST/WGT;
		TEMPBOTT=(XT^2+YT^2)^1.5;
		XTDD=-GM*XT/TEMPBOTT+AXT;
		YTDD=-GM*YT/TEMPBOTT+AYT;
		RTM1=XT-XM;
		RTM2=YT-YM;
		VTM1=XTD-XMD;
		VTM2=YTD-YMD;
		RTM=sqrt(RTM1^2+RTM2^2);
		VC=-(RTM1*VTM1+RTM2*VTM2)/RTM;
		TGO=RTM/VC;
		ACCDOTRTM=(XTDD*RTM1+YTDD*RTM2)/RTM;
		ACCPER1=XTDD-ACCDOTRTM*RTM1/RTM;
		ACCPER2=YTDD-ACCDOTRTM*RTM2/RTM;
		ACCPERPTOT=sqrt(ACCPER1^2+ACCPER2^2)/32.2;
		if T>TGUID
			TEMPBOTM=(XM^2+YM^2)^1.5;
			XMDDGRAV=-GM*XM/TEMPBOTM;
			YMDDGRAV=-GM*YM/TEMPBOTM;
			ZEM1=RTM1+VTM1*TGO+.5*(XTDD-XMDDGRAV)*TGO^2;
			ZEM2=RTM2+VTM2*TGO+.5*(YTDD-YMDDGRAV)*TGO^2;
			ZEMDOTRTM=(ZEM1*RTM1+ZEM2*RTM2)/RTM;
			ZEMPER1=ZEM1-ZEMDOTRTM*RTM1/RTM;
			ZEMPER2=ZEM2-ZEMDOTRTM*RTM2/RTM;
			ZEMPERPTOT=sqrt(ZEMPER1^2+ZEMPER2^2)/3280.;
			AXMGUID=XNP*ZEMPER1/(TGO^2);
			AYMGUID=XNP*ZEMPER2/(TGO^2);
			TGO=RTM/VC;
			if QGUID==0
				XNCLIM=0.;
			end
			if AXMGUID>XNCLIM
				AXMGUID=XNCLIM;
			elseif AXMGUID<-XNCLIM
				AXMGUID=-XNCLIM;
			end
			if AYMGUID>XNCLIM
				AYMGUID=XNCLIM;
			elseif AYMGUID<-XNCLIM
				AYMGUID=-XNCLIM;
			end
		else
			AXMGUID=0.;
			AYMGUID=0.;
		end
		if T>TLAUNCH
			TEMPBOTM=(XM^2+YM^2)^1.5;
			XMDD=-GM*XM/TEMPBOTM+AXMGUID;
			YMDD=-GM*YM/TEMPBOTM+AYMGUID;
		else
			XMDD=0.;
			YMDD=0.;
		end
		ACCNEW=sqrt(AXMGUID^2+AYMGUID^2);
		DELVD=ACCNEW;
		ALTMKM=(sqrt(XM^2+YM^2)-A)/3280.;
		FLAG=1;
	end
	FLAG=0;
	XT=.5*(XTOLD+XT+H*XTD);
	YT=.5*(YTOLD+YT+H*YTD);
	XTD=.5*(XTDOLD+XTD+H*XTDD);
	YTD=.5*(YTDOLD+YTD+H*YTDD);
	XM=.5*(XMOLD+XM+H*XMD);
	YM=.5*(YMOLD+YM+H*YMD);
	XMD=.5*(XMDOLD+XMD+H*XMDD);
	YMD=.5*(YMDOLD+YMD+H*YMDD);
	DELV=.5*(DELVOLD+DELV+H*DELVD);
	S=S+H;
	if QBOOST==1
		TGOLAM=TFTOT-T;
		[VRX,VRY,VRZ]=LAMBERT3D(XT,YT,ZT,TGOLAM,XF,YF,ZF,SWITCH1);
		VTX=VRX;
		VTY=VRY;
		DELVXT=VTX-XTD;
		DELVYT=VTY-YTD;
		VELT=sqrt(XTD^2+YTD^2);
		DELVELT=sqrt(DELVXT^2+DELVYT^2);
		if (T<TPZ & DELVELT>500.)
			AXT=ATP*DELVXT/DELVELT;
			AYT=ATP*DELVYT/DELVELT;
		elseif DELVELT<500.
			TRST=0.;
			QBOOST=0;
			AXT=0.;
			AYT=0.;
			XTD=VTX;
			XTDOLD=XTD;
			YTD=VTY;
			YTDOLD=YTD;
			TBOT=T;
		else
			QBOOST=0;
			QOOMPH=0;
			AXT=0.;
			AYT=0.;
			TBOT=T;
		end
	end
	if T<TUPT
		RTMAG=sqrt(XT^2+YT^2);
		AXT=ATP*XT/RTMAG;
		AYT=ATP*YT/RTMAG;
	end
	if T>=TLAUNCH
		TGOLAMM=TF-T;
		if QPERFECT==1
			XTF=XTFACT;
			YTF=YTFACT;
		elseif (QPERFECT==0 & QTAYLOR==1)
			TGOM=TF-T;
			XTF=XT+XTD*TGOM+.5*XTDD*TGOM*TGOM;
			YTF=YT+YTD*TGOM+.5*YTDD*TGOM*TGOM;
		end
		ZTF=0;
		QLAUNCH=1;
		PIPERR=sqrt((XTF-XTFACT)^2+(YTF-YTFACT)^2)/3280.;
	end
	TGOLAMM=TF-T;
	if (T>=TLAUNCH & QFIRST==1)
		QFIRST=0;
		TGOPZ=TF-TLAUNCH;
		[VRX,VRY,VRZ]=LAMBERT3D(XM,YM,ZM,TGOPZ,XTF,YTF,ZTF,SWITCHM);
		VMXRQD=VRX;
		VMYRQD=VRY;
		VMRQDKM=sqrt(VMXRQD^2+VMYRQD^2)/3280.;
		XMD=VMXRQD;
		XMDOLD=XMD;
		YMD=VMYRQD;
		YMDOLD=YMD;
	end
	if S>=(TS-.0001)
		S=0.;
		ALTTKM=(sqrt(XT^2+YT^2)-A)/3280.;
		DISTRTKM=distance3dkm(XT,YT,ZT,XFIRST,YFIRST,ZFIRST);
		ALTMKM=(sqrt(XM^2+YM^2)-A)/3280.;
		DISTRMKM=distance3dkm(XM,YM,ZM,XFIRST,YFIRST,ZFIRST);
		VTK=sqrt(XTD^2+YTD^2)/3280.;
		ATG=sqrt(XTDD^2+YTDD^2)/32.2;
		VMKM=sqrt(XMD^2+YMD^2)/3280.;
		VTKM=sqrt(XTD^2+YTD^2)/3280.;
		XLAM=atan2(RTM2,RTM1);
		ATPLOS=-XTDD*sin(XLAM)+YTDD*cos(XLAM);
		ATPLOSG=ATPLOS/32.2;
		ZEMPLOS=-ZEM1*sin(XLAM)+ZEM2*cos(XLAM);
		ZEMPLOSG=ZEMPLOS/3280.;
		XNCPLOSG=(-AXMGUID*sin(XLAM)+AYMGUID*cos(XLAM))/32.2;
		DELVKM=DELV/3280.;
		ACCNEWG=ACCNEW/32.2;
		AXMGUIDG=AXMGUID/32.2;
		AYMGUIDG=AYMGUID/32.2;
		if T>TLAUNCH
			PIPKM=sqrt((XTFACT-XTF)^2+(YTFACT-YTF)^2)/3280.;
			PIPPLOS=-(XTFACT-XTF)*sin(XLAM)+(YTFACT-YTF)*cos(XLAM);
			PIPPLOSKM=PIPPLOS/3280.;
		else
			PIPKM=0.;
			PIPPLOSKM=0.;
		end
		count=count+1;
		ArrayT(count)=T;
		ArrayDISTRTKM(count)=DISTRTKM;
		ArrayALTTKM(count)=ALTTKM;
		ArrayDISTRMKM(count)=DISTRMKM;
		ArrayALTMKM(count)=ALTMKM;
		ArrayATPLOSG(count)=ATPLOSG;
		ArrayXNCPLOSG(count)=XNCPLOSG;
		ArrayPIPPLOSKM(count)=PIPPLOSKM;
	end
end
figure
plot(ArrayDISTRTKM,ArrayALTTKM,ArrayDISTRMKM,ArrayALTMKM),grid
xlabel('Downrange (km)')
ylabel('Altitude (km) ')
figure
plot(ArrayT,ArrayATPLOSG,ArrayT,ArrayXNCPLOSG),grid
xlabel('Time (s)')
ylabel('Acceleration (g) ')
clc
output=[ArrayT',ArrayDISTRTKM',ArrayALTTKM',ArrayDISTRMKM',ArrayALTMKM',...
		ArrayATPLOSG',ArrayXNCPLOSG'];
save datfil.txt output -ascii
disp 'simulation finished'
DELV/3.28