function [VRX,VRY,VRZ]=LAMBERT3D(XT,YT,ZT,TF,XF,YF,ZF,SWITCH1)
PI=3.1415926535898;
DEG_PER_RAD=57.3;
EARTH_RADIUS=2.0926E7;
GM=1.4077E16	;		
HALFPI=PI/2.;
FT_PER_KM=3280.;
RAD_PER_SEC=1/57.3;
RF0X=XF-XT;
RF0Y=YF-YT;
RF0Z=ZF-ZT;
R0DOTRF=XT*XF+YT*YF+ZT*ZF;
R0DOTRF0=XT*RF0X+YT*RF0Y+ZT*RF0Z;
R0MAG=sqrt(XT^2+YT^2+ZT^2);
RFMAG=sqrt(XF^2+YF^2+ZF^2);
RF0MAG=sqrt(RF0X^2+RF0Y^2+RF0Z^2);
RATIO=R0MAG/RFMAG;
GMDIVR0=GM/R0MAG;
COS_T=R0DOTRF/(R0MAG*RFMAG);
VNUMER=GMDIVR0*(1.-COS_T);
T_MIN=0.;
if  SWITCH1==0 
	  G_MIN=HALFPI-acos(R0DOTRF0/(R0MAG*RF0MAG));
	  G_MAX=HALFPI;
	  THETA=acos(COS_T);
else
	  G_MIN=-HALFPI;
	  G_MAX=-HALFPI+acos(R0DOTRF0/(R0MAG*RF0MAG));
	  THETA=2.*PI-acos(COS_T);
end
SIN_T=sin(THETA);
COT_HALFT=1./tan(THETA/2.);
GAMMA=(G_MAX+G_MIN)/2.;
GOLD=G_MIN;
TOLD=0.;
T=0.;
ITERS=1;

S=.5*(R0MAG+RFMAG+RF0MAG);
BL=sqrt(R0MAG*RFMAG)*cos(THETA/2.)/S;
BT=sqrt(8.*GM/(S*S*S))*TF;

while (abs(TF-T)>(.00000001*TF))
	  SIN_G=sin(GAMMA);
	  COS_G=cos(GAMMA);
	  TAN_G=SIN_G/COS_G;
	  COS_TPLUSG=cos(THETA+GAMMA-2.*PI);
	  TERM1=(RATIO*COS_G-COS_TPLUSG)*COS_G;
	  RV0MAG=sqrt(VNUMER/TERM1);
	  LAMBDA=RV0MAG*RV0MAG/GMDIVR0;
	  if  LAMBDA<1.9999999 
	    TERM0=sqrt(2./LAMBDA-1.);
	    TERM1=(TAN_G*(1.-COS_T)+(1.-LAMBDA)*SIN_T)/...
			((2.-LAMBDA)*RATIO);
	    TERM2=(COS_G+COS_G)/(LAMBDA*TERM0*TERM0*TERM0);
	    TERM3= atan2(TERM0, (COS_G*COT_HALFT-SIN_G));
	    T=(R0MAG/(RV0MAG*COS_G))*(TERM1+TERM2*TERM3);
	  elseif  LAMBDA>2.0000001 
	    TERM0=sqrt(1.-2./LAMBDA);
	    TERM1=(TAN_G*(1.-COS_T)+(1.-LAMBDA)*SIN_T)/...
			((2.-LAMBDA)*RATIO);
	    TERM2=COS_G/(LAMBDA*TERM0*TERM0*TERM0);
	    TERM3=SIN_G-COS_G*COT_HALFT;
	    TERM3=log((TERM3-TERM0)/(TERM3+TERM0));
	    T=(R0MAG/(RV0MAG*COS_G))*(TERM1-TERM2*TERM3);
	  else
	    TERM0=COS_G*COT_HALFT;
	    TERM1=TERM0-SIN_G;
	    TERM0=(3*TERM0*TERM1+1.)/(TERM1*TERM1*TERM1);
	    T=TERM0*(2.*R0MAG)/(3.*RV0MAG);
	  end
	  if T>TF & GAMMA<G_MAX
	    G_MAX=GAMMA;
	  end

	  if T<0. & GAMMA<G_MAX
	    G_MAX=GAMMA;
	  end
	  if  T<TF & GAMMA>G_MIN
	    G_MIN=GAMMA;
	    T_MIN=T;
	  end
	  if (T<0.)
	    NEXT=(G_MIN+G_MAX)/2.;
	    GOLD=G_MIN;
	    TOLD=T_MIN;
	  else
	    NEXT=GAMMA+(TF-T)*(GAMMA-GOLD)/(T-TOLD);
	    if NEXT>=G_MAX 
	      NEXT=(GAMMA+G_MAX)/2.;
	    elseif NEXT<=G_MIN
	      NEXT=(GAMMA+G_MIN)/2.;
	    end
	    GOLD=GAMMA;
	    TOLD=T;
	  end
	  GAMMA=NEXT;
	  ITERS=ITERS+1;
      if ITERS>100
            break
      end
end
if SWITCH1==0
		GAMMA=GAMMA;
	ANGLE=HALFPI-GAMMA;
	SINA=sin(ANGLE);
	COSA=cos(ANGLE);
	V1X=XT;
	V1Y=YT;
	V1Z=ZT;
	V2X=XF;
	V2Y=YF;
	V2Z=ZF;
	MAG1=sqrt(V1X*V1X+V1Y*V1Y+V1Z*V1Z);
	DOTMAG=V1X*V2X+V1Y*V2Y+V1Z*V2Z;
	CROSSX=V1Y*V2Z-V1Z*V2Y;
	CROSSY=V1Z*V2X-V1X*V2Z;
	CROSSZ=V1X*V2Y-V1Y*V2X;
	CROSSMAG=sqrt(CROSSX*CROSSX+CROSSY*CROSSY+CROSSZ*CROSSZ);
	C2=MAG1*SINA/CROSSMAG;
	C1=COSA/MAG1-DOTMAG*C2/(MAG1*MAG1);
	RTEMPX=C1*V1X;
	RTEMPY=C1*V1Y;
	RTEMPZ=C1*V1Z;
	VUNITX=C2*V2X;
	VUNITY=C2*V2Y;
	VUNITZ=C2*V2Z;
	VUNITX=VUNITX+RTEMPX;
	VUNITY=VUNITY+RTEMPY;
	VUNITZ=VUNITZ+RTEMPZ;
else
	ANGLE=GAMMA-HALFPI;
	SINA=sin(ANGLE);
	COSA=cos(ANGLE);
	V1X=XT;
	V1Y=YT;
	V1Z=ZT;
	V2X=XF;
	V2Y=YF;
	V2Z=ZF;
	MAG1=sqrt(V1X*V1X+V1Y*V1Y+V1Z*V1Z);
	DOTMAG=V1X*V2X+V1Y*V2Y+V1Z*V2Z;
	CROSSX=V1Y*V2Z-V1Z*V2Y
	CROSSY=V1Z*V2X-V1X*V2Z;
	CROSSZ=V1X*V2Y-V1Y*V2X;
	CROSSMAG=sqrt(CROSSX*CROSSX+CROSSY*CROSSY+CROSSZ*CROSSZ);
	C2=MAG1*SINA/CROSSMAG;
	C1=COSA/MAG1-DOTMAG*C2/(MAG1*MAG1);
	RTEMPX=C1*V1X;
	RTEMPY=C1*V1Y;
	RTEMPZ=C1*V1Z;
	VUNITX=C2*V2X;
	VUNITY=C2*V2Y;
	VUNITZ=C2*V2Z;
	VUNITX=VUNITX+RTEMPX;
	VUNITY=VUNITY+RTEMPY;
	VUNITZ=VUNITZ+RTEMPZ;
end
VRX=RV0MAG*VUNITX;
VRY=RV0MAG*VUNITY;
VRZ=RV0MAG*VUNITZ;
